apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-scaler
spec:
  scaleTargetRef:
    deploymentName: kafka-consumer 
  cooldownPeriod: 30
  triggers: 
    - type: kafka
      metadata:
        bootstrapServers: kafka-broker.iterable.svc.cluster.local:9092
        consumerGroup: test-group
        topic: "quickstart-events"
        lagThreshold: '5'