apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-amqstreams-producer
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      name: kafka-amqstreams-producer
      labels:
        app: kafka-amqstreams-producer
    spec:
      restartPolicy: Never
      containers:
      - name: kafka-amqstreams-producer
        image: quay.io/zroubalik/kafka-app:latest
        command: [ "/kafkaproducerapp" ]      
        env:
          - name: BOOTSTRAP_SERVERS
            value: kafka-broker.iterable.svc:9092
          - name: TOPIC
            value: my-topic
          - name: MESSAGE_COUNT
            value: "150000"                    # increase this for a bigger load
          - name: DELAY_MS
            value: "10"