apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-consumer-scaledobject
spec:
  minReplicaCount: 0
  maxReplicaCount: 4
  cooldownPeriod: 5
  pollingInterval: 10
  fallback:
    failureThreshold: 3
    replicas: 1
  scaleTargetRef:
    name: kafka-consumer
  triggers:
  - type: kafka
    metadata:
      topic: "test-topic"
      bootstrapServers: "kafka-0.kafka-headless.default.svc.cluster.local:9092,kafka-1.kafka-headless.default.svc.cluster.local:9092,kafka-2.kafka-headless.default.svc.cluster.local:9092"
      consumerGroup: test-group
      lagThreshold: '5'
      offsetResetPolicy: 'latest'
