apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: iterable
  labels:
    deploymentName: kafka-quarkus-consumer
spec:
  scaleTargetRef:
    name: kafka-quarkus-consumer
  pollingInterval: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka-broker.iterable.svc:9092
        consumerGroup: my-group
        topic: my-topic
        # Optional
        lagThreshold: "50"
        offsetResetPolicy: latest