apiVersion: batch/v1
kind: Job
metadata:
  name: test-producer
  namespace: iterable
spec:
  parallelism: 5
  completions: 5
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: test-producer
        image: wurstmeister/kafka
        args: [ "--topic", "my-topic", "--throughput", "10000000", "--num-records", "1000000", "--producer-props", "bootstrap.servers=kafka-broker.iterable.svc.cluster.local:9092", "--record-size", "1000" ]
      restartPolicy: Never
  